apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app
  namespace: monitoring
  labels:
    monitoring: enabled
spec:
  namespaceSelector:
    matchNames:
      - applications
  selector:
    matchLabels:
      app: sample-app
  endpoints:
  - port: metrics
    interval: 15s 