---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    environment: dev
    type: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-services
  labels:
    environment: dev
    type: storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: applications
  labels:
    environment: dev
    type: workload 