apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: data-services
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: data-service
  template:
    metadata:
      labels:
        app: redis
        tier: data-service
    spec:
      containers:
      - name: redis
        image: redis:7.0-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: data-services
  labels:
    app: redis
    tier: data-service
spec:
  ports:
  - port: 6379
    targetPort: redis
    name: redis
  selector:
    app: redis
    tier: data-service 